### ISSUE TITLE
Typing _ before an atom clobbers the atom

### ISSUE THREAD

**Issue by unthingable** [LogtalkDotOrg/logtalk-for-vscode#6]
To reproduce:
1. Given editor text `foo(Bar)`, place cursor before `B`
2. Type `_`
3. `foo(Bar)` becomes `foo(_)`

Expected: `foo(Bar)` becomes `foo(_Bar)`.

**Comment by pmoura** [comment]
Same behavior in extensions for other programming languages (e.g. C++). Maybe there's a VSCode setting controlling this behavior...

**Comment by pmoura** [comment]
Fixed in 99325a7ff4436388d220949f8b65662d5d4756aa. This was a "feature" inherited from the original author of the extension, meant to replace a variable with an anonymous variable. But as implemented it also affected atoms. As users often write named anonymous variables instead of just `_`, this feature usefulness is rather limited and its behavior unexpected and annoying outside this single usage case.

**Comment by unthingable** [comment]
Many thanks. Seeing mentions of parentheses in the commit I wonder if that also fixes the deindent upon `)`, another annoying heritage.

**Comment by pmoura** [comment]
Please fill a separated issue for the de-indentation issue you mentioned with details on how to reproduce.
